src/Tweepics.Web/ViewModels/Home/HomeIndexViewModel.cs
using System.Collections.Generic;
using Tweepics.Web.Models;

namespace Tweepics.Web.ViewModels.Home
{
    public class HomeIndexViewModel
    {
        public List<string> Tags { get; set; }
        public TweetQueryInputModel TweetQueryInputModel { get; set; }
    }
}

src/Tweepics.Web/Controllers/DisplayController.cs
using Microsoft.AspNetCore.Mvc;
using Tweepics.Web.Models;
using Tweepics.Web.Services;
using Tweepics.Web.ViewModels.Display;

namespace Tweepics.Web.Controllers
{
    public class DisplayController : Controller
    {
        private ITweetResults _tweetResults;

        public DisplayController(ITweetResults tweetResults)
        {
            _tweetResults = tweetResults;
        }

        public IActionResult Tweets(TweetQueryInputModel inputQuery)
        {
            if (ModelState.IsValid)
            {
                TweetQueryModel query = new TweetQueryModel();
                query.QueryType = inputQuery.QueryType;
                query.OriginalQuery = inputQuery.OriginalQuery;
                query.Page = inputQuery.Page;
                query.FilterOptions = new FilterOptions
                {
                    Officials = inputQuery.Officials,
                    States = inputQuery.States,
                    Parties = inputQuery.Parties
                };

                DisplayTweetsViewModel model = _tweetResults.GetTweetResults(query);

                if (model == null)
                {
                    return View("TweetsNotFound");
                }

                return View(model);
            }
            else
            {
                // To do: Display validation errors
                return View("TweetsNotFound");
            }

        }
    }
}

src/Tweepics.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Tweepics.Web.Services;
using Tweepics.Web.Models;
using Tweepics.Web.ViewModels.Home;

namespace Tweepics.Web.Controllers
{
    public class HomeController : Controller
    {
        private ITags _tags;

        public HomeController(ITags tags)
        {
            _tags = tags;
        }

        public IActionResult Index()
        {
            HomeIndexViewModel model = new HomeIndexViewModel();
            model.Tags = _tags.GetAllTags();
            model.TweetQueryInputModel = new TweetQueryInputModel();

            return View(model);
        }
    }
}

src/Tweepics.Web/Views/Home/Index.cshtml
@using Tweepics.Web.ViewModels.Home;
@model HomeIndexViewModel

@{
    ViewBag.Title = "Tweepics";
    ViewBag.Body = "container-fluid home-page-background";
    ViewBag.Navbar = "navbar-home-page";
}

<h1 class="home-page-slogan">One Nation under Twitter</h1>
<div class="container-fluid">
    @Html.Partial("_Search", Model.TweetQueryInputModel)
</div>
<div class="vertical-center">
    <div class="container">
        @for (int i = 0; i < Model.Tags.Count; i += 3)
        {
            <div class="row tag-row">
                <div class="col-sm-4">
                    <a class="btn btn-block tag-buttons"
                       asp-action="Tweets" asp-controller="Display"
                       asp-route-originalquery="@Model.Tags[i]"
                       asp-route-querytype="tag">
                        @Model.Tags[i]
                    </a>
                </div>
                <div class="col-sm-4">
                    @if (i + 1 < Model.Tags.Count)
                    {
                        <a class="btn btn-block tag-buttons"
                           asp-action="Tweets" asp-controller="Display"
                           asp-route-originalquery="@Model.Tags[i + 1]"
                           asp-route-querytype="tag">
                            @Model.Tags[i + 1]
                        </a>
                    }
                    else
                    {
                        <div>
                        </div>
                    }
                </div>
                <div class="col-sm-4">
                    @if (i + 2 < Model.Tags.Count)
                    {
                        <a class="btn btn-block tag-buttons"
                           asp-action="Tweets" asp-controller="Display"
                           asp-route-originalquery="@Model.Tags[i + 2]"
                           asp-route-querytype="tag">
                            @Model.Tags[i + 2]
                        </a>
                    }
                    else
                    {
                        <div>
                        </div>
                    }
                </div>
            </div>
        }
    </div>
</div>

src/Tweepics.Web/Views/Home/_Search.cshtml
@using Tweepics.Web.Models;
@model TweetQueryInputModel

<div class="row justify-content-center">
    <div class="search-box">
        <form asp-controller="Display" asp-action="Tweets" method="get">
            <div class="input-group">
                <input type="text" placeholder="Search tweets" class="form-control search-text-input" asp-for="OriginalQuery" />
                <input type="hidden" asp-for="QueryType" value="search" />
                <div class="input-group-append">
                    <button type="submit" class="btn search-bar-button">Search</button>
                </div>
            </div>
        </form>
    </div>
</div>